### ISSUE TITLE
Error for generating image

### ISSUE THREAD

**Issue by PrijensNakrani** [ilovekimchi6/together-ai-dart#2]
I/flutter (10416): null
[together_ai_sdk.name] Error: Instance of 'UnknownServerError'

and also flux not available in imageModel

   generateImageFluz() async {
     final togetherAI = TogetherAISdk('0...APIKEY');
     final imageResponse = await togetherAI.imageGeneration('Group of cats', imageModel: ImageModel.stableDiffusionXL1_0);

     print("TOGATHORRR$imageResponse");
  }
  
  I'm calling the above method but it gives an error

**Comment by Apostletree42** [comment]
Hi @PrijensNakrani ,

I noticed you reported an issue with `imageGeneration`. It's working fine for me—did you manage to resolve it on your end?

Let me know if it’s still an issue or if you need further help!

**Comment by PrijensNakrani** [comment]
Yes, its working for me also ,I make some mistakes from my side so now it's working
